name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Deploy-GH-Pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: npm i -g pnpm
      - run: pnpm i
      - run: pnpm build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
